### ISSUE TITLE
Relocate under dafny-lang?

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/setup-dafny-action#1]
Hi @tchajed! I love this action, and couldn't resist using it in the CI for the Dafny standard library: https://github.com/dafny-lang/libraries :)

Would you be amenable to us moving it under the `dafny-lang` org, and making it more officially maintained as a Dafny feature?

**Comment by tchajed** [comment]
Sure, that sounds like a great thing! In order to transfer the repo you need permission to create a repo in the destination organization. I invited you as a collaborator in case you want to do the transfer, or you can give me permission and I'll do the transfer myself. GitHub should leave a redirect so downstream repos continue to work (presumably just mit-pdos/daisy-nfsd and dafny-lang/libraries, but who knows who else has discovered this).

**Comment by robin-aws** [comment]
Thanks @tchajed! I'm pretty sure I'd have to be an Admin to initiate the transfer myself though. Alternatively, you should be able to initiate the transfer and I can accept it on the `dafny-lang` side: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by tchajed** [comment]
Right, I guess you can't add an admin to a user account repo.

Transfers between user accounts just need approval, but transferring to an organization requires permission to create a new repo (I tried it and indeed got an error message about not being able to create a repo in dafny-lang).

**Comment by robin-aws** [comment]
I see. No worries, we've temporarily made you a member of `dafny-lang`, feel free to try the transfer again!

**Comment by tchajed** [comment]
Great, thanks for doing that @RustanLeino! I've transferred the repo and left the organization to save you the trouble.

**Comment by tchajed** [comment]
Ah it seems leaving the organization revoked my access to this repo so now I can't close the issue myself, could somebody add me back? Sorry about that!

**Comment by robin-aws** [comment]
Ha, no good deed goes unpunished. :) Thanks for helping us out @tchajed!
